// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaterBilling.Infrastructure.Persistence;

#nullable disable

namespace WaterBilling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WaterBillingDbContext))]
    partial class WaterBillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaterBilling.Domain.Billing.BillingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("InvoicesGenerated")
                        .HasColumnType("integer")
                        .HasColumnName("invoices_generated");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dry_run");

                    b.Property<int>("MetersConsidered")
                        .HasColumnType("integer")
                        .HasColumnName("meters_considered");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_utc");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_utc");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer")
                        .HasColumnName("skipped");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalBilledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_billed_amount");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_billing_runs");

                    b.HasIndex("TriggeredByUserId")
                        .HasDatabaseName("ix_billing_runs_triggered_by_user_id");

                    b.HasIndex("PeriodStartUtc", "StartedAtUtc")
                        .HasDatabaseName("ix_billing_runs_period_start_started_at");

                    b.ToTable("billing_runs", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.BillingRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_run_id");

                    b.Property<int>("ConsumptionFlags")
                        .HasColumnType("integer")
                        .HasColumnName("consumption_flags");

                    b.Property<decimal?>("ConsumptionM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("consumption_m3");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_billing_run_items");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_billing_run_items_invoice_id");

                    b.HasIndex("MeterId")
                        .HasDatabaseName("ix_billing_run_items_meter_id");

                    b.HasIndex("BillingRunId", "Outcome")
                        .HasDatabaseName("ix_billing_run_items_run_id_outcome");

                    b.ToTable("billing_run_items", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<Guid?>("BillingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_run_id");

                    b.Property<DateTimeOffset?>("ClosingReadingAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closing_reading_at_utc");

                    b.Property<decimal?>("ClosingTotalM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("closing_total_m3");

                    b.Property<int>("ConsumptionFlags")
                        .HasColumnType("integer")
                        .HasColumnName("consumption_flags");

                    b.Property<decimal>("ConsumptionM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("consumption_m3");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<decimal>("FixedCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_charge");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<DateTimeOffset?>("OpeningReadingAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opening_reading_at_utc");

                    b.Property<decimal?>("OpeningTotalM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("opening_total_m3");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_utc");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_utc");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_id");

                    b.Property<string>("PricingPlanName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pricing_plan_name");

                    b.Property<Guid?>("PricingPlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_version_id");

                    b.Property<int>("PricingPlanVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pricing_plan_version_number");

                    b.Property<int>("ReadingCount")
                        .HasColumnType("integer")
                        .HasColumnName("reading_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRatePercent")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("tax_rate_percent");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("UsageCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("usage_charge");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("BillingRunId")
                        .HasDatabaseName("ix_invoices_billing_run_id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_invoice_number_unique");

                    b.HasIndex("PricingPlanVersionId")
                        .HasDatabaseName("ix_invoices_pricing_plan_version_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_invoices_status");

                    b.HasIndex("CustomerId", "PeriodStartUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_invoices_customer_id_period_start");

                    b.HasIndex("MeterId", "PeriodStartUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_meter_id_period_start_unique");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("BandFromM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("band_from_m3");

                    b.Property<decimal?>("BandToM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("band_to_m3");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<decimal>("RatePerM3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_per_m3");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitsM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("units_m3");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_invoice_line_items");

                    b.HasIndex("InvoiceId", "SortOrder")
                        .HasDatabaseName("ix_invoice_line_items_invoice_id_sort_order");

                    b.ToTable("invoice_line_items", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("InitiatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at_utc");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_user_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_idempotency_key_unique")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.HasIndex("PaidByUserId")
                        .HasDatabaseName("ix_payments_paid_by_user_id");

                    b.HasIndex("Provider", "ProviderReference")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_provider_reference_unique")
                        .HasFilter("provider_reference IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(512)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_payment_events");

                    b.HasIndex("PaymentId", "OccurredAtUtc")
                        .HasDatabaseName("ix_payment_events_payment_id_occurred_at");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Common.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_email");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangesJson")
                        .HasMaxLength(512)
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Meters.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DesiredSupplyState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("desired_supply_state");

                    b.Property<DateTimeOffset>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at_utc");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("location_description");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_id");

                    b.Property<string>("ReportedSupplyState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reported_supply_state");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SupplyStateChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("supply_state_changed_at_utc");

                    b.Property<string>("SupplyStateReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("supply_state_reason");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_meters_customer_id");

                    b.HasIndex("PricingPlanId")
                        .HasDatabaseName("ix_meters_pricing_plan_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_meters_serial_number_unique")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Meters.MeterApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_meter_api_keys");

                    b.HasIndex("MeterId")
                        .HasDatabaseName("ix_meter_api_keys_meter_id");

                    b.HasIndex("Prefix")
                        .HasDatabaseName("ix_meter_api_keys_prefix");

                    b.ToTable("meter_api_keys", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_pricing_plans");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_plans_single_default")
                        .HasFilter("is_default = true AND deleted_at_utc IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_plans_name_unique")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("pricing_plans", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<decimal>("FixedCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_charge");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_id");

                    b.Property<decimal>("RatePerM3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_per_m3");

                    b.Property<string>("SlabMode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("slab_mode");

                    b.Property<decimal>("TaxRatePercent")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("tax_rate_percent");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_pricing_plan_versions");

                    b.HasIndex("PricingPlanId", "EffectiveFromUtc")
                        .HasDatabaseName("ix_pricing_plan_versions_plan_id_effective_from");

                    b.HasIndex("PricingPlanId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_plan_versions_plan_id_version_unique");

                    b.ToTable("pricing_plan_versions", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingSlab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<decimal>("FromM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("from_m3");

                    b.Property<Guid>("PricingPlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_version_id");

                    b.Property<decimal>("RatePerM3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_per_m3");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("ToM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("to_m3");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_pricing_slabs");

                    b.HasIndex("PricingPlanVersionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_slabs_version_id_sort_order_unique");

                    b.ToTable("pricing_slabs", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Readings.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anomalies")
                        .HasColumnType("integer")
                        .HasColumnName("anomalies");

                    b.Property<string>("AnomalyNotes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("anomaly_notes");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<decimal?>("FlowM3PerHour")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("flow_m3_per_hour");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<DateTimeOffset>("ReadingAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reading_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<decimal>("TotalM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("total_m3");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("MeterId", "ReadingAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_meter_readings_meter_id_reading_at_utc_unique");

                    b.ToTable("meter_readings", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Readings.MeterResetEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledged");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<decimal>("NewTotalM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("new_total_m3");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("notes");

                    b.Property<decimal>("PreviousTotalM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("previous_total_m3");

                    b.Property<Guid?>("TriggeringReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggering_reading_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_meter_reset_events");

                    b.HasIndex("MeterId", "DetectedAtUtc")
                        .HasDatabaseName("ix_meter_reset_events_meter_id_detected_at_utc");

                    b.ToTable("meter_reset_events", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("billing_address");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_unique")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.BillingRun", b =>
                {
                    b.HasOne("WaterBilling.Domain.Users.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_billing_runs_users_triggered_by_user_id");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.BillingRunItem", b =>
                {
                    b.HasOne("WaterBilling.Domain.Billing.BillingRun", "BillingRun")
                        .WithMany("Items")
                        .HasForeignKey("BillingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_billing_run_items_billing_runs_billing_run_id");

                    b.HasOne("WaterBilling.Domain.Billing.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_billing_run_items_invoices_invoice_id");

                    b.HasOne("WaterBilling.Domain.Meters.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_run_items_meters_meter_id");

                    b.Navigation("BillingRun");

                    b.Navigation("Invoice");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Invoice", b =>
                {
                    b.HasOne("WaterBilling.Domain.Billing.BillingRun", "BillingRun")
                        .WithMany()
                        .HasForeignKey("BillingRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invoices_billing_runs_billing_run_id");

                    b.HasOne("WaterBilling.Domain.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoices_users_customer_id");

                    b.HasOne("WaterBilling.Domain.Meters.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_meters_meter_id");

                    b.HasOne("WaterBilling.Domain.Pricing.PricingPlanVersion", "PricingPlanVersion")
                        .WithMany()
                        .HasForeignKey("PricingPlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoices_pricing_plan_versions_pricing_plan_version_id");

                    b.Navigation("BillingRun");

                    b.Navigation("Customer");

                    b.Navigation("Meter");

                    b.Navigation("PricingPlanVersion");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.InvoiceLineItem", b =>
                {
                    b.HasOne("WaterBilling.Domain.Billing.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_line_items_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Payment", b =>
                {
                    b.HasOne("WaterBilling.Domain.Billing.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.HasOne("WaterBilling.Domain.Users.User", "PaidBy")
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_paid_by_user_id");

                    b.Navigation("Invoice");

                    b.Navigation("PaidBy");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.PaymentEvent", b =>
                {
                    b.HasOne("WaterBilling.Domain.Billing.Payment", "Payment")
                        .WithMany("Events")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_events_payments_payment_id");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("WaterBilling.Domain.Meters.Meter", b =>
                {
                    b.HasOne("WaterBilling.Domain.Users.User", "Customer")
                        .WithMany("Meters")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meters_users_customer_id");

                    b.HasOne("WaterBilling.Domain.Pricing.PricingPlan", "PricingPlan")
                        .WithMany("Meters")
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meters_pricing_plans_pricing_plan_id");

                    b.Navigation("Customer");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("WaterBilling.Domain.Meters.MeterApiKey", b =>
                {
                    b.HasOne("WaterBilling.Domain.Meters.Meter", "Meter")
                        .WithMany("ApiKeys")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_api_keys_meters_meter_id");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingPlanVersion", b =>
                {
                    b.HasOne("WaterBilling.Domain.Pricing.PricingPlan", "PricingPlan")
                        .WithMany("Versions")
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_plan_versions_pricing_plans_pricing_plan_id");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingSlab", b =>
                {
                    b.HasOne("WaterBilling.Domain.Pricing.PricingPlanVersion", "PricingPlanVersion")
                        .WithMany("Slabs")
                        .HasForeignKey("PricingPlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_slabs_pricing_plan_versions_pricing_plan_version_id");

                    b.Navigation("PricingPlanVersion");
                });

            modelBuilder.Entity("WaterBilling.Domain.Readings.MeterReading", b =>
                {
                    b.HasOne("WaterBilling.Domain.Meters.Meter", "Meter")
                        .WithMany("Readings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_meters_meter_id");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("WaterBilling.Domain.Readings.MeterResetEvent", b =>
                {
                    b.HasOne("WaterBilling.Domain.Meters.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_reset_events_meters_meter_id");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.BillingRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WaterBilling.Domain.Billing.Payment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WaterBilling.Domain.Meters.Meter", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingPlan", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WaterBilling.Domain.Pricing.PricingPlanVersion", b =>
                {
                    b.Navigation("Slabs");
                });

            modelBuilder.Entity("WaterBilling.Domain.Users.User", b =>
                {
                    b.Navigation("Meters");
                });
#pragma warning restore 612, 618
        }
    }
}
