namespace WaterBilling.Domain.Readings;

/// <summary>How a reading entered the system. Kept on the row so that a disputed
/// invoice can be traced back to the ingestion path that produced it.</summary>
public enum ReadingSource
{
    /// <summary>POST to the REST ingestion endpoint by the device or its gateway.</summary>
    RestApi = 1,

    /// <summary>Bulk CSV upload (store-and-forward after a link outage).</summary>
    CsvUpload = 2,

    /// <summary>Manually entered by an admin (site visit, meter replacement).</summary>
    ManualEntry = 3,

    /// <summary>Generated by the demo seeder. Never present in production data.</summary>
    Seed = 99
}
