/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a bearer token
         * @description Returns a JWT carrying the user's role. Admin and Customer are distinguished by the role claim; meters do not log in here — they authenticate per-request with X-Meter-Key.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one meter reading
         * @description Authenticated with the per-meter X-Meter-Key header. Idempotent: re-posting a reading for a timestamp that already exists returns 200 with status 'duplicate_ignored' rather than an error, so a device that retries after a timeout is always safe.
         */
        post: operations["IngestReading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/readings/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit buffered readings
         * @description For devices that store and forward after a link outage. Each reading is processed independently, so one bad row does not discard the batch; the response reports the outcome of every reading.
         */
        post: operations["IngestReadingBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meters/{meterId}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List readings for a meter
         * @description Admins may read any meter. A customer may read only meters assigned to their own account; requesting another customer's meter returns 403, not 404, because the meter's existence is not itself a secret.
         */
        get: operations["GetMeterReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            tokenType: string;
            /** Format: date-time */
            expiresAtUtc: string;
            /** Format: uuid */
            userId: string;
            email: string;
            fullName: string;
            role: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description Batch form, for devices that store and forward after a link outage. */
        ReadingBatchRequest: {
            readings: components["schemas"]["ReadingRequest"][];
        };
        ReadingBatchResponse: {
            /** Format: uuid */
            meterId: string;
            meterSerial: string;
            /** Format: int32 */
            accepted: number;
            /** Format: int32 */
            duplicates: number;
            /** Format: int32 */
            rejected: number;
            results: components["schemas"]["ReadingIngestionResult"][];
        };
        /**
         * @description What happened to one submitted reading. `Status` is a stable machine token:
         *     `accepted`, `duplicate_ignored`, or `rejected`.
         */
        ReadingIngestionResult: {
            status: string;
            /** Format: date-time */
            readingAtUtc: string;
            /** Format: uuid */
            readingId?: null | string;
            /** @description Anomaly flags raised while storing, as readable tokens. */
            anomalies?: string[];
            message?: null | string;
        };
        ReadingPageResponse: {
            /** Format: uuid */
            meterId: string;
            serialNumber: string;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            readings: components["schemas"]["ReadingResponse"][];
        };
        /** @description A single observation posted by a meter. */
        ReadingRequest: {
            /**
             * Format: date-time
             * @description When the meter took the reading. Supplied by the device, not the server: a meter
             *     that buffers through a network outage must still report when each reading happened.
             */
            readingAtUtc: string;
            /**
             * Format: double
             * @description Cumulative volume in m3.
             */
            totalM3: number;
            /**
             * Format: double
             * @description Instantaneous flow in m3/hr. Optional, diagnostic only.
             */
            flowM3PerHour: null | number;
        };
        ReadingResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            readingAtUtc: string;
            /** Format: date-time */
            receivedAtUtc: string;
            /** Format: double */
            totalM3: number;
            /** Format: double */
            flowM3PerHour: null | number;
            source: string;
            anomalies: string;
            anomalyNotes: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaHttpValidationProblemDetails = components['schemas']['HttpValidationProblemDetails'];
export type SchemaLoginRequest = components['schemas']['LoginRequest'];
export type SchemaLoginResponse = components['schemas']['LoginResponse'];
export type SchemaProblemDetails = components['schemas']['ProblemDetails'];
export type SchemaReadingBatchRequest = components['schemas']['ReadingBatchRequest'];
export type SchemaReadingBatchResponse = components['schemas']['ReadingBatchResponse'];
export type SchemaReadingIngestionResult = components['schemas']['ReadingIngestionResult'];
export type SchemaReadingPageResponse = components['schemas']['ReadingPageResponse'];
export type SchemaReadingRequest = components['schemas']['ReadingRequest'];
export type SchemaReadingResponse = components['schemas']['ReadingResponse'];
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    IngestReading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingIngestionResult"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingIngestionResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    IngestReadingBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingBatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingBatchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMeterReadings: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                pageSize?: number;
                page?: number;
            };
            header?: never;
            path: {
                meterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingPageResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
